### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by InnovativeIdeas** [matztam/raymarine-evo-pilot-remote#3] opened 2022-09-12 15:20 UTC
I was wondering if the evo control pgns are documented anywhere 

Thanks 

Dave

**Comment by matztam** [comment] 2023-01-24 19:51
Unfortunately there is no documentation as these are proprietary NMEA commands. They have been reverse engineered based on the logs of Actisense Reader and by reading the code of [sbender9/signalk-raymarine-autopilot](https://github.com/sbender9/signalk-raymarine-autopilot). There are a lot of bytes added, whose function/meaning I do not know, as you can see in my code:
https://github.com/matztam/raymarine-evo-pilot-remote/blob/e8c536a0071045d61ae60944285aadb40e9b5139/RaymarinePilot.cpp#L15-L29

Duplicate of #1

**Closed as completed by matztam** 2023-01-24 19:51 UTC
